-- =====================================================
-- OWI (Outside World Interaction) Database Tables
-- Run these SQL scripts in your MySQL database
-- =====================================================

-- =====================================================
-- Table 1: Industry Advisor
-- =====================================================
CREATE TABLE IF NOT EXISTS faculty_industry_advisor (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255) NOT NULL,
    sig_number VARCHAR(100),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    industry_name VARCHAR(255) NOT NULL,
    domain_area VARCHAR(255),
    industry_type VARCHAR(100),
    industry_type_other VARCHAR(255),
    expert_name VARCHAR(255) NOT NULL,
    designation VARCHAR(255),
    email_id VARCHAR(255),
    phone_number VARCHAR(20),
    experience_years VARCHAR(50),
    area_of_expertise TEXT,
    industry_address TEXT,
    industry_website VARCHAR(255),
    frequency_of_interaction VARCHAR(50),
    date_of_meeting DATE,
    expense_incurred DECIMAL(10,2),
    suggestions TEXT,
    collaborative_activities TEXT,
    approval_document VARCHAR(500),
    owi_verification VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- =====================================================
-- Table 2: Laboratory by Industry
-- =====================================================
CREATE TABLE IF NOT EXISTS laboratory_by_industry (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255) NOT NULL,
    sig_number VARCHAR(100),
    task_id VARCHAR(100),
    name_of_laboratory VARCHAR(255) NOT NULL,
    collaborative_industry VARCHAR(255) NOT NULL,
    domain_area_of_industry VARCHAR(255),
    laboratory_area DECIMAL(10,2),
    total_amount_incurred DECIMAL(15,2),
    bit_contribution DECIMAL(15,2),
    financial_support_from_industry DECIMAL(15,2),
    equipment_sponsored TEXT,
    equipment_enhancement TEXT,
    layout_design_enhancement TEXT,
    curriculum_mapping TEXT,
    expected_outcomes TEXT,
    proof_document VARCHAR(500),
    owi_verification VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- =====================================================
-- Table 3: Professional Membership
-- =====================================================
CREATE TABLE IF NOT EXISTS professional_membership (
    id INT AUTO_INCREMENT PRIMARY KEY,
    membership_category VARCHAR(100),
    faculty VARCHAR(255) NOT NULL,
    task_id VARCHAR(100),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    name_of_professional_body VARCHAR(255) NOT NULL,
    membership_type VARCHAR(100),
    membership_id VARCHAR(255),
    name_of_grade_level_position VARCHAR(255),
    category VARCHAR(100),
    validity_type VARCHAR(100),
    apex_document_proof VARCHAR(500),
    amount DECIMAL(10,2),
    if_others VARCHAR(255),
    amount_if_others DECIMAL(10,2),
    document_proof VARCHAR(500),
    owi_verification VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- =====================================================
-- Table 4: Students Industrial Visit
-- =====================================================
CREATE TABLE IF NOT EXISTS students_industrial_visit (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255) NOT NULL,
    sig_number VARCHAR(100),
    task_id VARCHAR(100),
    programme VARCHAR(50),
    industry_name VARCHAR(255) NOT NULL,
    domain_area VARCHAR(255),
    industry_type VARCHAR(100),
    industry_type_other VARCHAR(255),
    industry_location TEXT,
    industry_website VARCHAR(255),
    contact_person_name VARCHAR(255),
    contact_person_designation VARCHAR(255),
    contact_person_email VARCHAR(255),
    contact_person_phone VARCHAR(20),
    visit_start_date DATE,
    visit_end_date DATE,
    year_of_study VARCHAR(50),
    number_of_students INT,
    male_students INT,
    female_students INT,
    purpose_of_visit TEXT,
    faculty1 VARCHAR(255),
    faculty2 VARCHAR(255),
    faculty3 VARCHAR(255),
    source_of_arrangement VARCHAR(100),
    curriculum_mapping TEXT,
    outcome_of_visit TEXT,
    proof_document VARCHAR(500),
    owi_verification VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- =====================================================
-- Table 5: Technical Societies
-- =====================================================
CREATE TABLE IF NOT EXISTS technical_societies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    society VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'Active',
    faculty VARCHAR(255),
    sig_number VARCHAR(100),
    task_id VARCHAR(100),
    owi_verification VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- =====================================================
-- Table 6: Training to Industry
-- =====================================================
CREATE TABLE IF NOT EXISTS training_to_industry (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255) NOT NULL,
    sig_number VARCHAR(100),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    event_name VARCHAR(255) NOT NULL,
    event_name_other VARCHAR(255),
    industry_name VARCHAR(255) NOT NULL,
    industry_address TEXT,
    domain_area VARCHAR(255),
    industry_type VARCHAR(100),
    industry_type_other VARCHAR(255),
    mode_of_training VARCHAR(50),
    industry_website VARCHAR(255),
    number_of_persons_trained INT,
    duration_days INT,
    start_date DATE,
    end_date DATE,
    outcome_of_training TEXT,
    honorarium_received DECIMAL(10,2),
    communication_proof VARCHAR(500),
    approval_letter VARCHAR(500),
    geotag_photos VARCHAR(500),
    participants_attendance VARCHAR(500),
    payment_proofs VARCHAR(500),
    consolidated_document VARCHAR(500),
    owi_verification VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- =====================================================
-- Table 7: Faculty External VIP Visit
-- =====================================================
CREATE TABLE IF NOT EXISTS faculty_external_vip_visit (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255),
    task_id VARCHAR(100),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    guest_belongs_to_industry VARCHAR(10),
    event_name VARCHAR(255),
    event_type VARCHAR(100),
    category VARCHAR(100),
    designation VARCHAR(255),
    organization_name VARCHAR(255),
    organization_address TEXT,
    start_date DATE,
    end_date DATE,
    purpose_of_visit TEXT,
    mobile_number VARCHAR(20),
    guest_email VARCHAR(255),
    department_visit VARCHAR(255),
    topic_presented TEXT,
    is_bit_alumni VARCHAR(10),
    formal_photo VARCHAR(500),
    photo_proof VARCHAR(500),
    approval_letter VARCHAR(500),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- =====================================================
-- Table 8: Faculty IRP Visit
-- =====================================================
CREATE TABLE IF NOT EXISTS faculty_irp_visit (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255),
    sig_number VARCHAR(100),
    task_id VARCHAR(100),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    number_of_faculty INT,
    claimed_for_faculty VARCHAR(255),
    claimed_for_department VARCHAR(255),
    type_of_approval VARCHAR(100),
    is_irp_visit_part_of_mou VARCHAR(10),
    mou_name VARCHAR(255),
    mou_points_discussed TEXT,
    from_date DATE,
    to_date DATE,
    mode_of_interaction VARCHAR(100),
    purpose_of_visit TEXT,
    amount_incurred DECIMAL(15,2),
    number_of_industry INT,
    apex_proof VARCHAR(500),
    geotag_photos VARCHAR(500),
    irp_form_signed VARCHAR(500),
    consolidated_document VARCHAR(500),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- =====================================================
-- Table 9: Faculty COE (Centre of Excellence)
-- =====================================================
CREATE TABLE IF NOT EXISTS faculty_coe (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255),
    sig_number VARCHAR(100),
    task_id VARCHAR(100),
    coe_name VARCHAR(255),
    centre_claimed_department VARCHAR(255),
    faculty_incharge VARCHAR(255),
    type_of_coe VARCHAR(100),
    collaborative_industry1 VARCHAR(255),
    collaborative_industry2 VARCHAR(255),
    area_in_sqm DECIMAL(10,2),
    domain VARCHAR(255),
    is_mou_part VARCHAR(10),
    mou_name VARCHAR(255),
    is_irp_result VARCHAR(10),
    irp_visits TEXT,
    stock_register_maintained VARCHAR(10),
    total_amount_incurred DECIMAL(15,2),
    bit_contribution DECIMAL(15,2),
    industry_contribution_with_gst DECIMAL(15,2),
    industry_contribution_without_gst DECIMAL(15,2),
    students_per_batch INT,
    academic_course TEXT,
    syllabus_document VARCHAR(500),
    lab_photo VARCHAR(500),
    communication_proof VARCHAR(500),
    apex_document VARCHAR(500),
    facilities_report VARCHAR(500),
    utilization_report VARCHAR(500),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- =====================================================
-- Table 10: Faculty Consultancy
-- =====================================================
CREATE TABLE IF NOT EXISTS faculty_consultancy (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty_id VARCHAR(255),
    faculty VARCHAR(255),
    task_id VARCHAR(100),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    faculty2_involved VARCHAR(10),
    faculty2 VARCHAR(255),
    faculty2_sig VARCHAR(100),
    faculty3_involved VARCHAR(10),
    faculty3 VARCHAR(255),
    faculty3_sig VARCHAR(100),
    faculty4_involved VARCHAR(10),
    faculty4 VARCHAR(255),
    faculty4_sig VARCHAR(100),
    faculty5_involved VARCHAR(10),
    faculty5 VARCHAR(255),
    faculty5_sig VARCHAR(100),
    consultancy_claiming_department VARCHAR(255),
    type_of_consultant VARCHAR(100),
    sector_of_consultant VARCHAR(100),
    organization_name VARCHAR(255),
    organization_address TEXT,
    core_sector VARCHAR(255),
    consultancy_project_title VARCHAR(255),
    consultancy_category VARCHAR(100),
    scope_of_work TEXT,
    duration_year INT,
    duration_month INT,
    duration_day INT,
    from_date DATE,
    to_date DATE,
    is_part_of_mou VARCHAR(10),
    mou_name VARCHAR(255),
    is_initiated_by_irp VARCHAR(10),
    irp_visits TEXT,
    is_fesem_related VARCHAR(10),
    is_roi_related VARCHAR(10),
    consultancy_amount DECIMAL(15,2),
    included_with_gst VARCHAR(10),
    amount_after_gst DECIMAL(15,2),
    ownership_rights_description TEXT,
    consultant_agreement_description TEXT,
    payment_date DATE,
    college_resources_utilized VARCHAR(10),
    resource_list TEXT,
    faculty_share_percentage DECIMAL(5,2),
    institute_share_percentage DECIMAL(5,2),
    college_transport_utilized VARCHAR(10),
    area_visited TEXT,
    distance_travelled DECIMAL(10,2),
    petrol_cost_per_km DECIMAL(10,2),
    transport_cost DECIMAL(10,2),
    college_consumables_utilized VARCHAR(10),
    consumables_list TEXT,
    consumables_charge DECIMAL(10,2),
    faculty_share_amount DECIMAL(15,2),
    institute_share_amount DECIMAL(15,2),
    net_faculty_share_amount DECIMAL(15,2),
    net_institute_share_amount DECIMAL(15,2),
    consultancy_agreement VARCHAR(500),
    communication_proof VARCHAR(500),
    audit_documents VARCHAR(500),
    work_logs VARCHAR(500),
    invoice_receipt VARCHAR(500),
    transaction_proof VARCHAR(500),
    geotag_photos VARCHAR(500),
    consultancy_report VARCHAR(500),
    consolidated_document VARCHAR(500),
    visiting_card VARCHAR(500),
    partnership_deed VARCHAR(500),
    noc_premises VARCHAR(500),
    non_disclosure_agreement VARCHAR(500),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- =====================================================
-- Table 11: Faculty Industry Projects
-- =====================================================
CREATE TABLE IF NOT EXISTS faculty_industry_projects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255),
    task_id VARCHAR(100),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    number_of_faculty INT,
    faculty2 VARCHAR(255),
    faculty2_sig VARCHAR(100),
    faculty3 VARCHAR(255),
    faculty3_sig VARCHAR(100),
    faculty4 VARCHAR(255),
    faculty4_sig VARCHAR(100),
    faculty5 VARCHAR(255),
    faculty5_sig VARCHAR(100),
    number_of_students INT,
    student1 VARCHAR(255),
    student2 VARCHAR(255),
    student3 VARCHAR(255),
    student4 VARCHAR(255),
    student5 VARCHAR(255),
    industry_name VARCHAR(255),
    type_of_industry VARCHAR(100),
    others_specify VARCHAR(255),
    industry_project VARCHAR(255),
    project_title VARCHAR(255),
    duration_months INT,
    start_date DATE,
    end_date DATE,
    outcome TEXT,
    industry_project_proof VARCHAR(500),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- =====================================================
-- Table 12: Faculty MoU (Memorandum of Understanding)
-- =====================================================
CREATE TABLE IF NOT EXISTS faculty_mou (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty_id VARCHAR(255),
    faculty VARCHAR(255),
    sig_number VARCHAR(100),
    task_id VARCHAR(100),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    mou_claiming_department VARCHAR(255),
    type_of_mou VARCHAR(100),
    type_of_industry VARCHAR(100),
    mou_based_on VARCHAR(100),
    domain_area VARCHAR(255),
    date_of_agreement DATE,
    duration VARCHAR(100),
    mou_effect_from DATE,
    mou_effect_till DATE,
    purpose_of_mou TEXT,
    legal_name_of_industry VARCHAR(255),
    industry_location VARCHAR(255),
    industry_address TEXT,
    industry_website VARCHAR(255),
    industry_contact VARCHAR(20),
    industry_email VARCHAR(255),
    scope_of_agreement TEXT,
    objectives_and_goals TEXT,
    boundaries_and_limitation TEXT,
    bit_roles_and_responsibilities TEXT,
    collaborator_roles_and_responsibilities TEXT,
    spoc_name VARCHAR(255),
    spoc_designation VARCHAR(255),
    spoc_email VARCHAR(255),
    spoc_phone VARCHAR(20),
    mou_signing_initiated_through VARCHAR(100),
    no_of_faculty INT,
    apex_proof VARCHAR(500),
    email_proof VARCHAR(500),
    signed_mou VARCHAR(500),
    party_rights VARCHAR(500),
    nondisclosure_affidavit VARCHAR(500),
    geotag_photos VARCHAR(500),
    all_documents VARCHAR(500),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- =====================================================
-- Table 13: Faculty Trained By Industry
-- =====================================================
CREATE TABLE IF NOT EXISTS faculty_trained_by_industry (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255),
    task_id VARCHAR(100),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    training_program_name VARCHAR(255),
    financial_assistance VARCHAR(100),
    amount_incurred DECIMAL(15,2),
    type_of_approval VARCHAR(100),
    apex_approval_no VARCHAR(100),
    industry_name VARCHAR(255),
    domain_area VARCHAR(255),
    type_of_industry VARCHAR(100),
    others_specify VARCHAR(255),
    mode_of_training VARCHAR(50),
    duration_in_days INT,
    start_date DATE,
    end_date DATE,
    industry_website VARCHAR(255),
    trainer1_name VARCHAR(255),
    trainer1_designation VARCHAR(255),
    trainer1_email VARCHAR(255),
    trainer1_phone VARCHAR(20),
    trainer2_applicable VARCHAR(10),
    trainer2_name VARCHAR(255),
    trainer2_designation VARCHAR(255),
    trainer2_email VARCHAR(255),
    trainer2_phone VARCHAR(20),
    outcome TEXT,
    proof_document VARCHAR(500),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

