-- Departments lookup table
CREATE TABLE IF NOT EXISTS departments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    department_name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default departments if table is empty
INSERT IGNORE INTO departments (department_name) VALUES
    ('Computer Science & Engineering'),
    ('Electronics & Communication Engineering'),
    ('Mechanical Engineering'),
    ('Civil Engineering'),
    ('Electrical & Electronics Engineering'),
    ('Information Technology'),
    ('Artificial Intelligence & Data Science'),
    ('Artificial Intelligence & Machine Learning'),
    ('Mathematics'),
    ('Physics'),
    ('Chemistry'),
    ('English'),
    ('Management Studies'),
    ('Master of Business Administration'),
    ('Master of Computer Applications');

CREATE TABLE IF NOT EXISTS faculty_mou (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255),
    sig_number VARCHAR(255),
    task_id VARCHAR(255),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    mou_claiming_department VARCHAR(255),
    type_of_mou VARCHAR(255),
    type_of_industry VARCHAR(255),
    mou_based_on VARCHAR(255),
    domain_area VARCHAR(255),
    date_of_agreement DATE,
    duration VARCHAR(255),
    mou_effect_from DATE,
    mou_effect_till DATE,
    purpose_of_mou TEXT,
    legal_name_of_industry VARCHAR(255),
    industry_location TEXT,
    industry_address TEXT,
    industry_website VARCHAR(255),
    industry_contact VARCHAR(255),
    industry_email VARCHAR(255),
    scope_of_agreement TEXT,
    objectives_and_goals TEXT,
    boundaries_and_limitation TEXT,
    bit_roles_and_responsibilities TEXT,
    collaborator_roles_and_responsibilities TEXT,
    spoc_name VARCHAR(255),
    spoc_designation VARCHAR(255),
    spoc_email VARCHAR(255),
    spoc_phone VARCHAR(255),
    mou_signing_initiated_through VARCHAR(255),
    no_of_faculty VARCHAR(50),
    apex_proof VARCHAR(255),
    email_proof VARCHAR(255),
    signed_mou VARCHAR(255),
    party_rights VARCHAR(255),
    nondisclosure_affidavit VARCHAR(255),
    geotag_photos VARCHAR(255),
    all_documents VARCHAR(255),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS faculty_irp_visit (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255),
    sig_number VARCHAR(255),
    task_id VARCHAR(255),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    number_of_faculty INT,
    claimed_for_faculty VARCHAR(255),
    claimed_for_department VARCHAR(255),
    type_of_approval VARCHAR(255),
    is_irp_visit_part_of_mou VARCHAR(10),
    mou_name VARCHAR(255),
    mou_points_discussed TEXT,
    from_date DATE,
    to_date DATE,
    mode_of_interaction VARCHAR(255),
    purpose_of_visit TEXT,
    amount_incurred DECIMAL(15, 2),
    number_of_industry INT,
    apex_proof VARCHAR(255),
    irp_form_signed VARCHAR(255),
    consolidated_document VARCHAR(255),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS faculty_trained_by_industry (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255),
    task_id VARCHAR(255),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    training_program_name VARCHAR(255),
    financial_assistance VARCHAR(255),
    amount_incurred DECIMAL(15, 2),
    type_of_approval VARCHAR(255),
    apex_approval_no VARCHAR(255),
    industry_name VARCHAR(255),
    domain_area VARCHAR(255),
    type_of_industry VARCHAR(255),
    others_specify VARCHAR(255),
    mode_of_training VARCHAR(255),
    duration_in_days INT,
    start_date DATE,
    end_date DATE,
    industry_website VARCHAR(255),
    trainer1_name VARCHAR(255),
    trainer1_designation VARCHAR(255),
    trainer1_email VARCHAR(255),
    trainer1_phone VARCHAR(255),
    trainer2_applicable VARCHAR(10),
    trainer2_name VARCHAR(255),
    trainer2_designation VARCHAR(255),
    trainer2_email VARCHAR(255),
    trainer2_phone VARCHAR(255),
    outcome TEXT,
    proof_document VARCHAR(255),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS faculty_industry_projects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty_id VARCHAR(255),
    faculty VARCHAR(255),
    task_id VARCHAR(255),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    number_of_faculty INT,
    faculty2 VARCHAR(255),
    faculty2_sig VARCHAR(255),
    faculty3 VARCHAR(255),
    faculty3_sig VARCHAR(255),
    faculty4 VARCHAR(255),
    faculty4_sig VARCHAR(255),
    faculty5 VARCHAR(255),
    faculty5_sig VARCHAR(255),
    number_of_students INT,
    student1 VARCHAR(255),
    student2 VARCHAR(255),
    student3 VARCHAR(255),
    student4 VARCHAR(255),
    student5 VARCHAR(255),
    industry_name VARCHAR(255),
    type_of_industry VARCHAR(255),
    others_specify VARCHAR(255),
    industry_project VARCHAR(255),
    project_title VARCHAR(255),
    duration_months INT,
    start_date DATE,
    end_date DATE,
    outcome TEXT,
    industry_project_proof VARCHAR(255),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS faculty_external_vip_visit (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255),
    task_id VARCHAR(255),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    guest_belongs_to_industry VARCHAR(10),
    event_name VARCHAR(255),
    event_type VARCHAR(255),
    category VARCHAR(255),
    designation VARCHAR(255),
    organization_name VARCHAR(255),
    organization_address TEXT,
    start_date DATE,
    end_date DATE,
    purpose_of_visit TEXT,
    mobile_number VARCHAR(20),
    guest_email VARCHAR(255),
    department_visit TEXT,
    topic_presented TEXT,
    is_bit_alumni VARCHAR(10),
    formal_photo VARCHAR(255),
    photo_proof VARCHAR(255),
    approval_letter VARCHAR(255),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS faculty_coe (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255),
    sig_number VARCHAR(255),
    task_id VARCHAR(255),
    coe_name VARCHAR(255),
    centre_claimed_department VARCHAR(255),
    faculty_incharge VARCHAR(255),
    type_of_coe VARCHAR(255),
    collaborative_industry1 VARCHAR(255),
    collaborative_industry2 VARCHAR(255),
    area_in_sqm DECIMAL(10, 2),
    domain VARCHAR(255),
    is_mou_part VARCHAR(10),
    mou_name VARCHAR(255),
    is_irp_result VARCHAR(10),
    irp_visits TEXT,
    stock_register_maintained VARCHAR(10),
    total_amount_incurred DECIMAL(15, 2),
    bit_contribution DECIMAL(15, 2),
    industry_contribution_with_gst DECIMAL(15, 2),
    industry_contribution_without_gst DECIMAL(15, 2),
    students_per_batch INT,
    academic_course VARCHAR(255),
    syllabus_document VARCHAR(255),
    lab_photo VARCHAR(255),
    communication_proof VARCHAR(255),
    apex_document VARCHAR(255),
    facilities_report VARCHAR(255),
    utilization_report VARCHAR(255),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS faculty_consultancy (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faculty VARCHAR(255),
    task_id VARCHAR(255),
    special_labs_involved VARCHAR(10),
    special_lab VARCHAR(255),
    faculty2_involved VARCHAR(10),
    faculty2 VARCHAR(255),
    faculty2_sig VARCHAR(255),
    faculty3_involved VARCHAR(10),
    faculty3 VARCHAR(255),
    faculty3_sig VARCHAR(255),
    faculty4_involved VARCHAR(10),
    faculty4 VARCHAR(255),
    faculty4_sig VARCHAR(255),
    faculty5_involved VARCHAR(10),
    faculty5 VARCHAR(255),
    faculty5_sig VARCHAR(255),
    consultancy_claiming_department VARCHAR(255),
    type_of_consultant VARCHAR(255),
    sector_of_consultant VARCHAR(255),
    organization_name VARCHAR(255),
    organization_address TEXT,
    core_sector VARCHAR(255),
    consultancy_project_title VARCHAR(255),
    consultancy_category VARCHAR(255),
    scope_of_work VARCHAR(255),
    duration_year INT,
    duration_month INT,
    duration_day INT,
    from_date DATE,
    to_date DATE,
    is_part_of_mou VARCHAR(10),
    mou_name VARCHAR(255),
    is_initiated_by_irp VARCHAR(10),
    irp_visits TEXT,
    is_fesem_related VARCHAR(10),
    is_roi_related VARCHAR(10),
    consultancy_amount DECIMAL(15, 2),
    included_with_gst VARCHAR(10),
    amount_after_gst DECIMAL(15, 2),
    ownership_rights_description TEXT,
    consultant_agreement_description TEXT,
    payment_date DATE,
    college_resources_utilized VARCHAR(10),
    resource_list TEXT,
    faculty_share_percentage DECIMAL(5, 2),
    institute_share_percentage DECIMAL(5, 2),
    college_transport_utilized VARCHAR(10),
    area_visited TEXT,
    distance_travelled DECIMAL(10, 2),
    petrol_cost_per_km DECIMAL(10, 2),
    transport_cost DECIMAL(15, 2),
    college_consumables_utilized VARCHAR(10),
    consumables_list TEXT,
    consumables_charge DECIMAL(15, 2),
    faculty_share_amount DECIMAL(15, 2),
    institute_share_amount DECIMAL(15, 2),
    net_faculty_share_amount DECIMAL(15, 2),
    net_institute_share_amount DECIMAL(15, 2),
    consultancy_agreement VARCHAR(255),
    communication_proof VARCHAR(255),
    audit_documents VARCHAR(255),
    work_logs VARCHAR(255),
    invoice_receipt VARCHAR(255),
    transaction_proof VARCHAR(255),
    geotag_photos VARCHAR(255),
    consultancy_report VARCHAR(255),
    consolidated_document VARCHAR(255),
    visiting_card VARCHAR(255),
    partnership_deed VARCHAR(255),
    noc_premises VARCHAR(255),
    non_disclosure_agreement VARCHAR(255),
    verification_status VARCHAR(50) DEFAULT 'Initiated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
