const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
require('dotenv').config();
const app = express();
app.use(bodyParser.json());
app.use(cors());
// const roomRoutes = require('./src/routes/roomRoutes');
// app.use('/api/room', roomRoutes);
module.exports = app;